---
- name: "samba | Gather services facts"
  ansible.builtin.service_facts:
- name: "samba | Set facts about ctdb service"
  ansible.builtin.set_fact:
    samba_ctdb_service_facts:
      "{{ hostvars[inventory_hostname]['services']['ctdb.service']['state'] }}"
  failed_when:
    - "hostvars[inventory_hostname]['services']['ctdb.service']['state'] is
      defined"
    - "hostvars[inventory_hostname]['services']['ctdb.service']['state'] in
      ['', [], None]"
