---
- name: "samba | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "samba | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['samba'] is defined"
    - "hostvars[inventory_hostname]['samba'] != ''"
    - "hostvars[inventory_hostname]['samba'] |
       community.general.json_query(vars['samba_install_package']) is defined"
    - "hostvars[inventory_hostname]['samba'] |
       community.general.json_query(vars['samba_install_package']) == 'true'"
  vars:
    samba_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "samba | Include ctdb pre requisite tasks"
  ansible.builtin.include_tasks:
    file: "ctdb_prereq.yml"
  when:
    - "vars['samba_mode'] == 'cluster'"
- name: "samba | Include samba deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy.d/samba.yml"
- name: "samba | Include ctdb deployment tasks"
  ansible.builtin.include_tasks:
    file: "deploy.d/ctdb.yml"
  when:
    - "vars['samba_mode'] == 'cluster'"
