---
- ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['samba'] is defined"
    - "hostvars[inventory_hostname]['samba'] != ''"
    - "hostvars[inventory_hostname]['samba'] |
       community.general.json_query(vars['samba_install_package']) is defined"
    - "hostvars[inventory_hostname]['samba'] |
       community.general.json_query(vars['samba_install_package']) == 'true'"
  vars:
    samba_install_package: "[] | map(&install_package || 'false', @) | [0]"
- ansible.builtin.include_tasks:
    file: "ctdb_prereq.yml"
  when:
    - "vars['samba_mode'] == 'cluster'"
- ansible.builtin.import_tasks:
    file: "deploy_samba.yml"
- ansible.builtin.include_tasks:
    file: "deploy_ctdb.yml"
  when:
    - "vars['samba_mode'] == 'cluster'"
